wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1710417206.870552
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      - 35
      4: 3.10.4
      5: 0.13.2
      8:
      - 5
